WAWJS_ROOT = File.expand_path('../../../', __FILE__)
WAWJS = Dir["#{WAWJS_ROOT}/dist/waw-*.js"].last
require 'fileutils'

# Absolutizes a path from here (i.e. __DIR__)
def _(relative) 
  File.expand_path("../#{relative}", __FILE__)
end

begin
  require 'rake/testtask'
  desc "Run unit tests"
  Rake::TestTask.new(:unit_test) do |t|
    t.libs = ["src"]
    t.verbose = false
    # Glob pattern to match test files. (default is 'test/test*.rb')
    t.pattern = "test/*_test.rb"
  end
rescue LoadError => ex
  task :unit_test do
    abort 'rspec is not available. In order to run spec, you must: gem install rspec'
  end
ensure
  desc "Run all tests"
  task :test => [:unit_test]
end

desc "Builds the application (gallery.coffee -> gallery.js)"
task :build do
  # Copy the last waw.js version 
  puts `cd #{WAWJS_ROOT} && cake dist`
  FileUtils.cp WAWJS, _("src/public/js")

  # Compile the application
  puts `../../bin/wCompile --join src > src/public/js/gallery.js`
end

desc "Runs the application"
task :"run" => :build do
  Kernel.exec "./config.ru"
end

task :default => :"run"